pyDataverse/__init__.py,sha256=3tn157rCVRoZFvLFJ9u_648L6ETwiF2TEqvMEDSJ7Hg,662
pyDataverse/api.py,sha256=nvd6QTVJD1H9WWFCsm-t0m6N5ynA1Vn6xLHThqZFYtw,31276
pyDataverse/exceptions.py,sha256=8Iv4vpkZEjoCBRPXTh1rYjRePEsQblTFuzbwQQVUvtg,1245
pyDataverse/models.py,sha256=PN1UfxyhBvS4nJxMHCgrB-FZG-_GLHSjEAHVa-fGD1g,3422
pyDataverse/utils.py,sha256=1TnQt_ma3lGstNE5s88yQGnN96MCyVM2wm0xspt7iu0,2985
pyDataverse-0.1.0.dist-info/LICENSE.txt,sha256=Xl16upLSKrLry-DFwuMXafkn2qX74B47V7jIs-3d4LE,1112
pyDataverse-0.1.0.dist-info/METADATA,sha256=bbLomcwhDZMks0PhizATO7JugAOIqjE2_eVI7ozN0TE,3110
pyDataverse-0.1.0.dist-info/WHEEL,sha256=h_aVn5OB2IERUjMbi2pucmR_zzWJtk303YXvhh60NJ8,110
pyDataverse-0.1.0.dist-info/top_level.txt,sha256=Xh1_quu-yMF5-EUGNoZTxuovh6lJwSY2sw5PpaSRCpI,12
pyDataverse-0.1.0.dist-info/RECORD,,
