msgid ""
msgstr ""
"Project-Id-Version: red-discordbot\n"
"POT-Creation-Date: 2018-04-02 17:36+AKDT\n"
"PO-Revision-Date: 2018-04-15 16:41-0400\n"
"Last-Translator: Kowlin <boxedpp@gmail.com>\n"
"Language-Team: Spanish\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: ENCODING\n"
"Generated-By: pygettext.py 1.5\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: crowdin.com\n"
"X-Crowdin-Project: red-discordbot\n"
"X-Crowdin-Language: es-ES\n"
"X-Crowdin-File: /core/locales/messages.pot\n"
"Language: es_ES\n"

#: ../cog_manager.py:313
msgid "Install Path: {}\n\n"
msgstr "Ruta de instalación: {}\n\n"

#: ../cog_manager.py:329
msgid "That path does not exist or does not point to a valid directory."
msgstr "Esa ruta es no existe o no apunta a un directorio válido."

#: ../cog_manager.py:338
msgid "Path successfully added."
msgstr "Ruta añadida exitósamente."

#: ../cog_manager.py:351
msgid "That is an invalid path number."
msgstr "Número de ruta inválido."

#: ../cog_manager.py:355
msgid "Path successfully removed."
msgstr "Ruta eliminada exitósamente."

#: ../cog_manager.py:371
msgid "Invalid 'from' index."
msgstr "Índice 'from' no válido."

#: ../cog_manager.py:377
msgid "Invalid 'to' index."
msgstr "Índice 'to' no válido."

#: ../cog_manager.py:381
msgid "Paths reordered."
msgstr "Rutas reordenadas."

#: ../cog_manager.py:399
msgid "That path does not exist."
msgstr "Ruta inexistente."

#: ../cog_manager.py:403
msgid "The bot will install new cogs to the `{}` directory."
msgstr "El bot instalará nuevos cogs en el directorio '{}'."

#: ../core_commands.py:171
msgid "Embeds are now {} by default."
msgstr ""

#: ../core_commands.py:193 ../core_commands.py:218
msgid "Embeds will now fall back to the global setting."
msgstr ""

#: ../core_commands.py:197
msgid "Embeds are now {} for this guild."
msgstr ""

#: ../core_commands.py:222
msgid "Embeds are now {} for you."
msgstr ""

#: ../core_commands.py:483
msgid "Shutting down... "
msgstr "Apagando... "

#: ../core_commands.py:498
msgid "Restarting..."
msgstr "Reiniciando..."

#: ../core_commands.py:556
msgid "The admin role for this guild has been set."
msgstr "El rol de administrador para este gremio ha sido configurado."

#: ../core_commands.py:564
msgid "The mod role for this guild has been set."
msgstr "El rol de moderador para este gremio ha sido configurado."

#: ../core_commands.py:577
msgid "Failed. Remember that you can edit my avatar up to two times a hour. The URL must be a direct link to a JPG / PNG."
msgstr "Error. Recuerde que puede editar mi avatar hasta dos veces por hora. La URL debe ser un enlace directo a un JPG o PNG."

#: ../core_commands.py:581
msgid "JPG / PNG format only."
msgstr "Únicamente formatos JPG o PNG."

#: ../core_commands.py:583 ../core_commands.py:680 ../core_commands.py:694
msgid "Done."
msgstr "Listo."

#: ../core_commands.py:598
msgid "Game set."
msgstr "Juego configurado."

#: ../core_commands.py:613
msgid "Listening set."
msgstr "Escuchando junto."

#: ../core_commands.py:628
msgid "Watching set."
msgstr "Viendo junto."

#: ../core_commands.py:657
msgid "Status changed to {}."
msgstr ""

#: ../core_commands.py:689
msgid "Failed to change name. Remember that you can only do it up to 2 times an hour. Use nicknames if you need frequent changes. `{}set nickname`"
msgstr "No se pudo cambiar el nombre. Recuerde que śolo se puede hacer hasta 2 veces por hora. Utilizar sobrenombres si cambios más frecuentes son necesarios. `{}set nickname`"

#: ../core_commands.py:704
msgid "I lack the permissions to change my own nickname."
msgstr "No tengo permisos para cambiar mi propio sobrenombre."

#: ../core_commands.py:718 ../core_commands.py:731
msgid "Prefix set."
msgstr "Prefijo configurado."

#: ../core_commands.py:727
msgid "Guild prefixes have been reset."
msgstr "Prefijos de gremio han sido restaurados."

#: ../core_commands.py:750
msgid "\n"
"Verification token:"
msgstr "\n"
"Código de verificación:"

#: ../core_commands.py:753
msgid "Remember:\n"
msgstr "Recuerda:\n"

#: ../core_commands.py:756
msgid "I have printed a one-time token in the console. Copy and paste it here to confirm you are the owner."
msgstr "He impreso un código de uso único en la consola. Copie y péguelo acá para confirmar que es el dueño."

#: ../core_commands.py:764
msgid "The set owner request has timed out."
msgstr "El tiempo de espera para configuración de dueño se ha agotado."

#: ../core_commands.py:770
msgid "You have been set as owner."
msgstr "Ha sido configurado como dueño."

#: ../core_commands.py:772
msgid "Invalid token."
msgstr "Código inválido."

#: ../core_commands.py:787
msgid "Please use that command in DM. Since users probably saw your token, it is recommended to reset it right now. Go to the following link and select `Reveal Token` and `Generate a new token?`.\n\n"
"https://discordapp.com/developers/applications/me/{}"
msgstr ""

#: ../core_commands.py:810
msgid "Locale has been set."
msgstr "Configuración regional establecida."

#: ../core_commands.py:824
msgid "Done. Sentry logging is now enabled."
msgstr "Hecho. Ya está habilitado el inicio del robot."

#: ../core_commands.py:827
msgid "Done. Sentry logging is now disabled."
msgstr "Hecho. Ya está deshabilitado el inicio del robot."

#: ../core_commands.py:880
msgid "A backup has been made of this instance. It is at {}."
msgstr ""

#: ../core_commands.py:884
msgid "That directory doesn't seem to exist..."
msgstr ""

#: ../core_commands.py:894
msgid "User ID: {}"
msgstr ""

#: ../core_commands.py:897
msgid "through DM"
msgstr "a través de MP"

#: ../core_commands.py:899
msgid "from {}"
msgstr "de {}"

#: ../core_commands.py:900
msgid " | Server ID: {}"
msgstr ""

#: ../core_commands.py:909
msgid "Use `{}dm {} <text>` to reply to this user"
msgstr "Utilice `{}dm {} <texto>` para responder a este usuario"

#: ../core_commands.py:912
msgid "Sent by {} {}"
msgstr "Enviado por {} {}"

#: ../core_commands.py:930 ../core_commands.py:943
msgid "I cannot send your message, I'm unable to find my owner... *sigh*"
msgstr "No puedo enviar el mensaje, soy incapaz de encontrar a mi dueño... *suspiro*"

#: ../core_commands.py:933 ../core_commands.py:946
msgid "I'm unable to deliver your message. Sorry."
msgstr "No soy capaz de entregar su mensaje. Lo siento."

#: ../core_commands.py:935 ../core_commands.py:948
msgid "Your message has been sent."
msgstr "Su mensaje ha sido enviado."

#: ../core_commands.py:962
msgid "Invalid ID or user not found. You can only send messages to people I share a server with."
msgstr "ID o usuario no encontrado. Sólo puede enviar mensajes a personas con quienes comparto un servidor."

#: ../core_commands.py:970
msgid "Owner of {}"
msgstr ""

#: ../core_commands.py:971
msgid "You can reply to this message with {}contact"
msgstr ""

#: ../core_commands.py:984 ../core_commands.py:993
msgid "Sorry, I couldn't deliver your message to {}"
msgstr ""

#: ../core_commands.py:987 ../core_commands.py:996
msgid "Message delivered to {}"
msgstr ""

#: ../core_commands.py:1016
msgid "User added to whitelist."
msgstr "Usuario añadido a la lista blanca."

#: ../core_commands.py:1025
msgid "Whitelisted Users:"
msgstr "Usuarios en lista blanca:"

#: ../core_commands.py:1045
msgid "User has been removed from whitelist."
msgstr "El usuario ha sido removido de la lista blanca."

#: ../core_commands.py:1047
msgid "User was not in the whitelist."
msgstr "El usuario no estaba en la lista blanca."

#: ../core_commands.py:1055
msgid "Whitelist has been cleared."
msgstr "La lista blanca ha sido borrada."

#: ../core_commands.py:1072
msgid "You cannot blacklist an owner!"
msgstr "No puedes poner un dueño en la lista negra!"

#: ../core_commands.py:1079
msgid "User added to blacklist."
msgstr "Usuario ha añadido a la lista negra."

#: ../core_commands.py:1088
msgid "blacklisted Users:"
msgstr "usuarios en la lista negra:"

#: ../core_commands.py:1108
msgid "User has been removed from blacklist."
msgstr "El usuario se ha eliminado de la lista negra."

#: ../core_commands.py:1110
msgid "User was not in the blacklist."
msgstr "El usuario no estaba en la lista negra."

#: ../core_commands.py:1118
msgid "blacklist has been cleared."
msgstr "la lista negra ha sido borrada."

#: ../dev_commands.py:213
msgid "Already running a REPL session in this channel. Exit it with `quit`."
msgstr "Este canal ya está ejecutando una sesión REPL. Salga usando `quit`."

#: ../dev_commands.py:218
msgid "Enter code to execute or evaluate. `exit()` or `quit` to exit."
msgstr "Ingresar código a ejecutar o evaluar. `exit()` o `quit` para salir."

#: ../dev_commands.py:281
msgid "Unexpected error: `{}`"
msgstr "Error inesperado: `{}`"

